Feat/jpa post
No-Break/personal-kotlin pull request #2
Opened 2021-08-07 15:14 UTC by OseongminO

RESTl API 익숙해지는 연습을 하고자 합니다. 
수정,삭제,조회도 추가하면서 지금은 파라미터를 모두 변수로 받고있는데
일괄로 받아서 처리할수있는 방법을 찾아 수정하도록 하겠습니다.

2021-08-09 20:09 UTC, choiwonho approved these changes
전반적으로  띄어쓰기만 확인해주시면 될 것 같습니다. 고생하셨습니다!

2021-08-09 20:09 UTC, choiwonho commented on src/main/kotlin/schedule/service/ScheduleService.kt
> +    fun addSchedule(title:String,authority:String,appointedtime:String,checkAlarm:String) : Schedule
띄어쓰기 규칙 맞춰주시면 좋을것 같습니다!

2021-08-10 14:26 UTC, abcshc requested changes
고생하셨습니다. 
pull request의 이름을 문장 형태로 해당 작업의 내용을 짧고 간단한 설명으로 작성하는게 좋을 것 같습니다.

**.gitignore 설정 부탁드립니다.**
`.gradle`, `.idea`, `build` 등 작성한 코드 외의 파일이 포함되지 않도록 부탁드립니다.
https://www.toptal.com/developers/gitignore 를 참고해도 좋을 것 같습니다.

2021-08-10 14:26 UTC, abcshc commented on src/main/kotlin/schedule/controller/ScheduleController.kt
> +                    @RequestParam(value="checkAlarm")checkAlarm:String):ResponseEntity<Schedule>{
Nit: 파라미터의 이름과 변수명이 같다면 별도로 value를 지정해주지 않아도 되는 것으로 알고 있습니다.

2021-08-25 06:22 UTC, merged